# Auto-generated Terraform backend configuration
# Generated by bootstrap-aws.sh on Mon Feb  2 14:30:12 EST 2026

terraform {
  backend "s3" {
    bucket         = "ollystack-terraform-state-us-east-2"
    key            = "ollystack/dev/terraform.tfstate"
    region         = "us-east-2"
    encrypt        = true
    dynamodb_table = "ollystack-terraform-lock"
  }
}
